# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_api', '0003_auto_20170620_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
