# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_api', '0005_auto_20170620_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id_distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor_api.Distributor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
