# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_api', '0007_remove_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='PIR', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributor_api.Distributor'),
        ),
    ]
