# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_api', '0008_auto_20170620_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id_distributor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='distributor_api.Distributor'),
        ),
    ]
