# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_api', '0010_remove_sensor_id_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='id_distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributor_api.Distributor'),
        ),
    ]
