# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_api', '0011_sensor_id_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id_distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor_api.Distributor'),
        ),
    ]
